--3
UPDATE EMPLOYEES 
SET COMMISSION=0
WHERE COMMISSION IS NULL 
SELECT EMPLOYEE_int,FIRST_NAME,LAST_NAME, DATEDIFF(YEAR, BIRTH_DATE, GETDATE()) AS 'Employee_age' , DATEDIFF(YEAR,HIRE_DATE, GETDATE()) AS ' Employee  Seniority' from EMPLOYEES where ((SALARY+COMMISSION) >= 8000)  order by DATEDIFF(DAY,HIRE_DATE, GETDATE()) DESC 
--4
select PRODUCT_REF,PRODUCT_NAME,SUPPLIER_int,UNITS_ON_ORDER,UNIT_PRICE from PRODUCTS  WHERE QUANTITY LIKE '%bottles%' AND UPPER(PRODUCT_NAME) LIKE '__T%' AND SUPPLIER_int IN (1,2,3) AND UNIT_PRICE BETWEEN 70 AND 200 AND UNITS_ON_ORDER IS NOT NULL
--5
select * 
from CUSTOMERS 
WHERE CUSTOMER_CODE IN (SELECT c.CUSTOMER_CODE
						FROM CUSTOMERS c
						INNER JOIN SUPPLIERS s ON s.CITY=c.CITY AND s.COUNTRY=c.COUNTRY AND RIGHT(s.POSTAL_CODE,3) = RIGHT(c.POSTAL_CODE,3) 
						WHERE s.SUPPLIER_int=1)
--6
SELECT ORDER_int,
	  CASE 
		WHEN UNIT_PRICE*QUANTITY BETWEEN 0 AND 2000 THEN 0.05
		WHEN UNIT_PRICE*QUANTITY BETWEEN 2001 AND 10000 THEN 0.1
		WHEN UNIT_PRICE*QUANTITY BETWEEN 10001 AND 40000 THEN 0.15
		ELSE 0.2
		END AS 'new discount rate',
      CASE 
		WHEN ORDER_int BETWEEN 10000 and 10999 THEN 'apply old discount rate' 
		ELSE 'apply new discount rate'
		END AS 'discount rate application note'			
FROM ORDER_DETAILS
WHERE ORDER_int BETWEEN 10998 AND 11003
--7
SELECT s.SUPPLIER_int,s.COMPANY,s.ADDRESS,s.PHONE
FROM SUPPLIERS s
INNER JOIN PRODUCTS p ON p.SUPPLIER_int=s.SUPPLIER_int
WHERE p.CATEGORY_CODE=1
--8
SELECT c.CUSTOMER_CODE
FROM CUSTOMERS c
WHERE CITY = 'Berlin' AND c.CUSTOMER_CODE IN ((SELECT c.CUSTOMER_CODE
							FROM CUSTOMERS c
							INNER JOIN ORDERS o ON  o.CUSTOMER_CODE=c.CUSTOMER_CODE 
							INNER JOIN ORDER_DETAILS od ON o.ORDER_int=od.ORDER_int
							INNER JOIN PRODUCTS p ON p.PRODUCT_REF=od.PRODUCT_REF
							WHERE p.CATEGORY_CODE=3 AND ((SELECT COUNT(o.ORDER_int)
														FROM ORDER_DETAILS od
														inner join ORDERS o on o.ORDER_int=od.ORDER_int
														where o.CUSTOMER_CODE=c.CUSTOMER_CODE) <=1)
							GROUP BY c.CUSTOMER_CODE))						
SELECT * FROM ORDERS
--9
SELECT c.CUSTOMER_CODE,c.COMPANY,c.PHONE, COUNT(o.ORDER_int) AS 'total amount of orders they placed every Monday in April 1998',c.COUNTRY
FROM CUSTOMERS c
INNER JOIN ORDERS o ON  o.CUSTOMER_CODE=c.CUSTOMER_CODE 
INNER JOIN ORDER_DETAILS od ON o.ORDER_int=od.ORDER_int 
WHERE c.COUNTRY='France ' AND MONTH(o.ORDER_DATE)=4 AND YEAR(o.ORDER_DATE)=1998 AND DATEPART(WEEKDAY,o.ORDER_DATE) = 2
GROUP BY c.CUSTOMER_CODE,c.COMPANY,c.PHONE,c.COUNTRY;
--10
SELECT c.CUSTOMER_CODE,c.COMPANY,c.PHONE,COUNT(od.PRODUCT_REF) AS 'number of products'
FROM CUSTOMERS c
INNER JOIN ORDERS o ON  o.CUSTOMER_CODE=c.CUSTOMER_CODE 
INNER JOIN ORDER_DETAILS od ON o.ORDER_int=od.ORDER_int 
GROUP BY c.CUSTOMER_CODE,c.COMPANY,c.PHONE
HAVING COUNT(DISTINCT od.PRODUCT_REF)=(SELECT COUNT(DISTINCT PRODUCT_REF)
								FROM PRODUCTS)
--11
SELECT c.CUSTOMER_CODE,COUNT(od.ORDER_int) AS 'number of orders'
FROM CUSTOMERS c
INNER JOIN ORDERS od ON od.CUSTOMER_CODE=c.CUSTOMER_CODE
WHERE c.COUNTRY='Fance' 
GROUP BY c.CUSTOMER_CODE
--12
DECLARE @c INT;
DECLARE @v INT;
SET @c =(SELECT COUNT(ORDER_int) 
FROM ORDERS
WHERE YEAR(ORDER_DATE)=1996)
SET @v =(SELECT COUNT(ORDER_int) 
FROM ORDERS
WHERE YEAR(ORDER_DATE)=1997)
SELECT @c AS 'number of orders 1996',@v AS 'number of orders 1997',@v-@c 'difference';







